### ISSUE TITLE
Feature / Architecture Discussion: Ref

### ISSUE THREAD

**Issue by siegfriedpammer** [icsharpcode/ILSpy#1151]
# Language Feature(s):
* [x] C# 7.0 ref locals / ref returns
* [x] C# 7.2 ref readonly
* [x] C# 7.2 interior pointer/Span/ref struct
* [x] C# 7.2 conditional ref operator
* [x] C# 7.3 Ref local re-assignment

# TODO:
* [ ] Add tests

These features should be implemented in one go, because they depend on each other. Some of them are already implemented partially (e.g. conditional ref and basic support for ref variables).

## 1) Ref locals / Ref returns

I have been unable to find a specification for this feature, but here is some info:
Scope of ref locals/parameters and returns: https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md#draft-language-specification
Roslyn test cases: http://source.roslyn.codeplex.com/#Roslyn.Compilers.CSharp.Semantic.UnitTests/Semantics/RefLocalsAndReturnsTests.cs

## 2) Ref readonly

Seems to be fairly well documented at https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/readonly-ref.md...

## 3) interior pointer/Span/ref struct

See https://github.com/dotnet/csharplang/blob/master/proposals/csharp-7.2/span-safety.md

## 4) conditional ref operator

Should already be done.

## 5) Ref local re-assignment

Needs syntactic adjustment, because the syntax currently used by ILSpy is invalid. See #1147.
